# Generated by Django 2.2 on 2019-10-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(max_length=400, verbose_name='Ответ'),
        ),
    ]
