# Generated by Django 2.2 on 2019-10-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191019_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choice_poll', to='webapp.Poll', verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_choice', to='webapp.Choice', verbose_name='ответ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_poll', to='webapp.Poll', verbose_name='Вопрос')),
            ],
        ),
    ]
